export const requiredTables = [
  "leads",
  "lead_profiles",
  "lead_scores",
  "lead_events",
  "conversations",
  "messages",
  "campaigns",
  "campaign_leads",
  "experiments",
  "experiment_assignments",
  "claims",
  "jobs",
  "job_attempts",
  "ai_calls",
  "channel_locks",
  "do_not_contact",
  "offers",
  "orders",
  "credentialing",
  "certifications",
  "territories",
  "settings",
  "audit_logs",
] as const;
