import { z } from "zod";

export const salesDecisionSchema = z.object({
  lead_id: z.string(),
  intent: z.enum([
    "interested",
    "asked_training",
    "asked_credentialing",
    "asked_price",
    "asked_kit",
    "asked_products",
    "asked_representation",
    "has_project",
    "has_customer",
    "uses_competitor",
    "wants_whatsapp",
    "has_cnpj",
    "no_cnpj",
    "not_owner",
    "will_forward",
    "objection",
    "not_interested",
    "opt_out",
    "ambiguous",
    "needs_human",
  ]),
  action: z.enum([
    "reply",
    "ask_question",
    "qualify",
    "present_company",
    "present_training",
    "present_credentialing",
    "explore_business",
    "explore_existing_projects",
    "explore_current_solution",
    "present_portfolio_opportunity",
    "send_whatsapp_handoff",
    "schedule_followup",
    "wait",
    "close",
    "escalate_human",
  ]),
  message: z.string().max(900).nullable(),
  reason: z.string().max(500),
  confidence: z.number().min(0).max(1),
  human_review_required: z.boolean(),
  next_funnel_stage: z.string().nullable(),
});

export type SalesDecision = z.infer<typeof salesDecisionSchema>;
